@startuml

!define DEFAULT_BGCOLOR #9cc3da
!define ITP_DARK_BLUE #322960

skinparam defaultFontColor Black
skinparam defaultFontName SansSerif
skinparam defaultFontSize 12
skinParam defaultFontStyle plain

' values: otho, polyline, splines (default)
skinparam linetype ortho

skinparam arrow {
  Color ITP_DARK_BLUE
  FontColor ITP_DARK_BLUE
  'FontName
  'FontSize
  'FontStyle
  'LollipopColor
  'MessageAlignment
  'Thickness
}

skinparam class {
  BackgroundColor DEFAULT_BGCOLOR
  BorderColor ITP_DARK_BLUE
  'FontColor #ffffff
  'FontName Flama Semicondensed
  'FontSize 16
  FontStyle bold
}

skinparam component {
  ArrowFontName Flama Semicondensed
  ArrowColor ITP_DARK_BLUE
  ArrowFontColor ITP_DARK_BLUE
  BackgroundColor DEFAULT_BGCOLOR
  BorderColor ITP_DARK_BLUE
  'FontColor #ffffff
  'FontName Flama Semicondensed
  'FontSize 10
  ' style: plain, bold, italic
  'FontStyle bold
  Style uml2  
}

skinparam database {
  BackgroundColor DEFAULT_BGCOLOR
  
}

skinparam node {
  BackgroundColor DEFAULT_BGCOLOR
}


@enduml