@startuml

!define ITP_DARK_BLUE #322960

skinparam class {
  BackgroundColor #9cc3da
  BorderColor ITP_DARK_BLUE
  'FontColor #ffffff
  'FontName Flama Semicondensed
  'FontSize 16
  'FontWeight bold
}

skinparam component {
  ArrowFontName Flama Semicondensed
  ArrowColor ITP_DARK_BLUE
  ArrowFontColor ITP_DARK_BLUE
  BackgroundColor #9cc3da
  BorderColor ITP_DARK_BLUE
  'FontColor #ffffff
  'FontName Flama Semicondensed
  'FontSize 10
  'FontWeight bold
  Style uml2  
}

skinparam database {
  
}

skinparam linetype ortho

skinparam node {

}



@enduml